##  template for a Welcome message to be emailed to class (delete this line)
From: teacher@somewhere.edu (Jan Teacher)
Reply-To: teacher@somewhere.edu
Subject: online homework for Math 123
Message:
    Hi $FN,

Your course is at
	http://webwork.elearning.ubc.ca/webwork2/MATH101

Please use your CWL to login to the WeBWorK.

Some help pages about WeBWorK are at URL
	http://webwork.maa.org/wiki/Category:Students

Have fun.

Take care,
TJ
